version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd Assignment2
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lambdas
      - mv lf1.js index.js
      - zip -g ../../deployment_package_1.zip index.js
      - mv index.js lf1.js
      - mv lf2.js index.js
      - zip -g ../../deployment_package_2.zip index.js
      - mv index.js lf2.js

  post_build:
    commands:
      - echo "Updating lambda Functions..."
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://../../deployment_package_2.zip
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://../../deployment_package_1.zip
      - echo "DONE!!"
